[database]
# Available drivers: neon, supabase, postgres_local
driver = "postgres_local"
description = "Database operations driver selection"

[database.drivers.neon]
description = "Neon serverless Postgres"
required_env = ["NEON_API_KEY", "NEON_PROJECT_ID"]

[database.drivers.supabase]
description = "Supabase managed Postgres"
required_env = ["SUPABASE_URL", "SUPABASE_SERVICE_KEY", "SUPABASE_PROJECT_REF"]

[database.drivers.postgres_local]
description = "Local PostgreSQL instance"
required_env = ["POSTGRES_HOST", "POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD"]

[frontend]
# Available drivers: vercel, netlify
driver = "vercel"
description = "Frontend deployment driver selection"

[frontend.drivers.vercel]
description = "Vercel deployment platform"
required_env = ["VERCEL_TOKEN"]

[frontend.drivers.netlify]
description = "Netlify deployment platform"
required_env = ["NETLIFY_ACCESS_TOKEN"]

[backend]
# Available drivers: render, flyio
driver = "render"
description = "Backend deployment driver selection"

[backend.drivers.render]
description = "Render cloud platform"
required_env = ["RENDER_API_KEY"]

[backend.drivers.flyio]
description = "Fly.io deployment platform"
required_env = ["FLY_ACCESS_TOKEN"]

[logging]
# Whether to redact secrets in logs
redact_secrets = true
# Log driver selection events
log_driver_selection = true