[system]
version = "1.0.0"
default_bay = "database"

[core]
# Core modules are always loaded
modules = ["fs", "git", "exec", "heir", "sidecar", "registry"]
enabled = true

[intake]
# Intake modules are always loaded
modules = ["ingest", "mapping"]
enabled = true

[bays]
# Selected bay is loaded based on BAY environment variable or default_bay
available = ["database", "frontend", "backend"]

[logging]
level = "INFO"
format = "json"