[bay]
name = "backend"
description = "Backend development and deployment bay"
enabled = true

[modules]
domains = ["backend"]

[tools]
scaffold = { module = "domains.backend", enabled = true }
lint = { module = "domains.backend", enabled = true }
test = { module = "domains.backend", enabled = true }
container_build = { module = "domains.backend", enabled = true }
deploy = { module = "domains.backend", enabled = true }
cron_schedule = { module = "domains.backend", enabled = true }