[bay]
name = "frontend"
description = "Frontend development and deployment bay"
enabled = true

[modules]
domains = ["frontend"]

[tools]
scaffold = { module = "domains.frontend", enabled = true }
build = { module = "domains.frontend", enabled = true }
preview = { module = "domains.frontend", enabled = true }
deploy = { module = "domains.frontend", enabled = true }
routes_sync = { module = "domains.frontend", enabled = true }